version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: diff-demo-chrome
    network_mode: host
    environment:
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    shm_size: 2g