name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build Astro site
      run: bun run build

    - name: Start static server
      run: bunx http-server dist -p 4321 &
      shell: bash

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        bunx chromedriver --version

    - name: Wait for server to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:4321 > /dev/null; then
            echo "Server is ready"
            break
          fi
          echo "Waiting for server... ($i/30)"
          sleep 1
        done

    - name: Run Nightwatch tests
      run: bun run test:e2e:ci

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
        retention-days: 30